### ISSUE TITLE
Broken icon in AppImage?

### ISSUE THREAD

**Issue by probonopd** [AaronErhardt/qfsm#2]
Hello @AaronErhardt, thanks for making an AppImage. However, `usr/share/icons/hicolor/48x48/apps/qfsm.png` seems to be broken entirely?

Reference:
https://github.com/AppImage/appimage.github.io/pull/2140

**Comment by AaronErhardt** [comment]
Thanks for submitting this issue. The icons seemingly have been broken since I ported Qfsm to git. I replaced them with the icons from an older release from the Sourceforge page of Qfsm and the AppImage is now recompiled with the old but correct icons (which still looks slightly ugly, I think Qfsm generally needs a new and modern app-icon).

Please let me know whether all issue with the AppImage are solved with the new version :)

Just out of curiosity: How did you find this repo? Do you use Qfsm and if you do for which task? I've been maintaining Qfsm just for a few months now so I'm always looking for feedback.

**Comment by probonopd** [comment]
Hello @AaronErhardt thanks for the fix. I am looking at projects that are using the AppImage format and try to help them. Whenever I find an AppImage, I run it through an automated test at https://github.com/AppImage/appimage.github.io. I will re-run the test with your latest release.

**Comment by probonopd** [comment]
So please ping me once a release containing the fix is available for download. Thanks! :+1:

**Comment by AaronErhardt** [comment]
@probonopd the fixed version should be updated on the release page. I just replaced the old version with the freshly compiled one: [https://github.com/AaronErhardt/qfsm/releases/download/0.55/Qfsm-0_55-x86_64.AppImage](https://github.com/AaronErhardt/qfsm/releases/download/0.55/Qfsm-0_55-x86_64.AppImage)

**Comment by probonopd** [comment]
Thank you very much @AaronErhardt. Any chance you could build on xenial or earlier? Currently it refuses to run on xenial, which is still a supported distribution:

https://github.com/AppImage/appimage.github.io/pull/2149

**Comment by AaronErhardt** [comment]
@probonopd yes, I think I can fire up a VM with Xenial. This might take some time, however.

**Comment by AaronErhardt** [comment]
@probonopd I uploaded the new AppImage built under Xenial to the release page. The url is the same: [https://github.com/AaronErhardt/qfsm/releases/download/0.55/Qfsm-0_55-x86_64.AppImage](https://github.com/AaronErhardt/qfsm/releases/download/0.55/Qfsm-0_55-x86_64.AppImage)

I hope this time everything works :)

**Comment by probonopd** [comment]
Yes, everything worked, thank you :+1:  

https://github.com/AppImage/appimage.github.io/pull/2149

**Comment by AaronErhardt** [comment]
Thank you, as well :)
